In [1]:
import numpy as np

In [6]:
# ndim：维度
# shape：行数和列数
# size：元素个数
array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵
print(array)

[[1 2 3]
 [2 3 4]]


In [10]:
print(array.shape)
print(array.size)
print(array.ndim)

(2, 3)
6
2


In [17]:
# array：创建数组
# dtype：指定数据类型
# zeros：创建数据全为0
# ones：创建数据全为1
# empty：创建数据接近0
# arange：按指定范围创建数据
# linspace：创建线段
a = np.zeros((3,4)) # 数据全为0，3行4列
print(a)
b = np.linspace(1,10,20)    # 开始端1，结束端10，且分割成20个数据，生成线段
print(b)
c=np.arange(5)
print("arange",c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
arramge [0 1 2 3 4]


In [20]:
#矩阵计算 + - * 
a=np.array([10,20,30,40])   # array([10, 20, 30, 40])
b=np.arange(4)     # array([0, 1, 2, 3])
c=a-b
print(c)
d=a+b
print(d)
e=b**2 #乘方
print(e)

[10 19 28 37]
[10 21 32 43]
[0 1 4 9]


In [24]:
#reshape 重构矩阵
b=np.arange(4).reshape((2,2))
print(b)

[[0 1]
 [2 3]]


In [22]:
import numpy as np
a=np.random.random((2,4))
print(a)
# array([[ 0.94692159,  0.20821798,  0.35339414,  0.2805278 ],
#       [ 0.04836775,  0.04023552,  0.44091941,  0.21665268]])
print("a =",a)
# a = [[ 0.23651224  0.41900661  0.84869417  0.46456022]
# [ 0.60771087  0.9043845   0.36603285  0.55746074]]

print("sum =",np.sum(a,axis=1))
# sum = [ 1.96877324  2.43558896]

print("min =",np.min(a,axis=0))
# min = [ 0.23651224  0.41900661  0.36603285  0.46456022]

print("max =",np.max(a,axis=1))
# max = [ 0.84869417  0.9043845 ]

[[0.83623771 0.36915694 0.9073825  0.03908433]
 [0.17471848 0.12545419 0.37237404 0.49936002]]
a = [[0.83623771 0.36915694 0.9073825  0.03908433]
 [0.17471848 0.12545419 0.37237404 0.49936002]]
sum = [2.15186149 1.17190673]
min = [0.17471848 0.12545419 0.37237404 0.03908433]
max = [0.9073825  0.49936002]


In [29]:
#argmin() 和 argmax() 两个函数分别对应着求矩阵中最小元素和最大元素的索引。
import numpy as np
A = np.arange(2,14).reshape((3,4)) 
# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])
print(np.argmin(A))    # 0
print(np.argmax(A))    # 11

0
11


In [31]:
print(np.mean(A))        # 均值
print(np.median(A))       # 中位数

7.5
7.5


In [32]:
#索引
A = np.arange(3,15)

# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
         
print(A[3])    # 6

6


In [35]:
A = np.arange(3,15).reshape((3,4))
"""
array([[ 3,  4,  5,  6]
       [ 7,  8,  9, 10]
       [11, 12, 13, 14]])
"""
         
print(A[2])        #矩阵A中第三行(从0开始算第一行)的所有元素 
# [11 12 13 14]
print(A[1][1])      # 8
print(A[1, 1:3])    # [8 9]

[11 12 13 14]
8
[8 9]


In [36]:
#切片输出
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


'    \n[ 3,  4,  5, 6]\n[ 7,  8,  9, 10]\n[11, 12, 13, 14]\n'

In [37]:
#逐列打印
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [39]:
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B)))    # vertical stack本身属于一种上下合并，即对括号中的两个整体进行对应操作
D = np.hstack((A,B))       # horizontal stack D本身来源于A，B两个数列的左右合并，而且新生成的D

print(D) 
# [1,1,1,2,2,2]

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


In [40]:
A = np.arange(12).reshape((3, 4))
print(A)
"""
array([[ 0,  1,  2,  3],
    [ 4,  5,  6,  7],
    [ 8,  9, 10, 11]])
"""

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


'\narray([[ 0,  1,  2,  3],\n    [ 4,  5,  6,  7],\n    [ 8,  9, 10, 11]])\n'

In [43]:
#纵向分割
print(np.split(A, 2, axis=1))
#横向分割
print(np.split(A, 3, axis=0))
#不等量分割
print(np.array_split(A, 3, axis=1)) # # 沿轴1将数组分成3个子数组 axis: 指定要分割的轴。默认值为 0。

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
